create table if not exists public.birthday_messages (id bigint generated by default as identity primary key,name text not null check (char_length(trim(name)) between 2 and 80),location text check (location is null or char_length(location) <= 80),message text not null check (char_length(trim(message)) between 3 and 600),created_at timestamptz not null default now());
alter table public.birthday_messages enable row level security;
grant select, insert on public.birthday_messages to anon, authenticated;
drop policy if exists "Anyone can read celebration messages" on public.birthday_messages;
create policy "Anyone can read celebration messages" on public.birthday_messages for select to anon, authenticated using (true);
drop policy if exists "Anyone can post celebration messages" on public.birthday_messages;
create policy "Anyone can post celebration messages" on public.birthday_messages for insert to anon, authenticated with check (char_length(trim(name)) between 2 and 80 and char_length(trim(message)) between 3 and 600 and (location is null or char_length(location) <= 80));
create index if not exists birthday_messages_created_at_idx on public.birthday_messages (created_at desc);