(function(){
const countdown=document.querySelector('#countdown'),eventDate=countdown?new Date(countdown.dataset.event).getTime():0;
const els={days:document.querySelector('#days'),hours:document.querySelector('#hours'),minutes:document.querySelector('#minutes'),seconds:document.querySelector('#seconds')};
function tick(){if(!countdown)return;const diff=Math.max(0,eventDate-Date.now());els.days.textContent=String(Math.floor(diff/86400000)).padStart(2,'0');els.hours.textContent=String(Math.floor(diff/3600000)%24).padStart(2,'0');els.minutes.textContent=String(Math.floor(diff/60000)%60).padStart(2,'0');els.seconds.textContent=String(Math.floor(diff/1000)%60).padStart(2,'0');if(!diff){const heading=document.querySelector('.countdown-heading strong');if(heading)heading.textContent='Today we celebrate!'}}
tick();setInterval(tick,1000);
const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('#site-nav');if(toggle&&nav){toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');toggle.setAttribute('aria-expanded','false')}))}
function openWhatsApp(message,number='26662025872'){window.open('https://wa.me/'+number+'?text='+encodeURIComponent(message),'_blank','noopener,noreferrer')}
const reservationForm=document.querySelector('#reservationForm');
if(reservationForm)reservationForm.addEventListener('submit',function(e){e.preventDefault();const d=new FormData(this),m=['Hello Mokorosi Family,','','I would like to make a reservation for Mme Mokorosi’s 100th Birthday Celebration.',`Name: ${d.get('name')}`,`Number of guests: ${d.get('guests')}`,`Contact number: ${d.get('phone')}`,d.get('note')?`Special note: ${d.get('note')}`:'','','Event: 31 October 2026 at 12:00 noon','Venue: BESA Meat & Chill, Corner Moshoeshoe & Caledon, Maseru West','Reservation contacts: +266 6202 5871 / +266 6202 5872'].filter(Boolean).join('\n');openWhatsApp(m)});
const guestbookForm=document.querySelector('#guestbookForm');
if(guestbookForm)guestbookForm.addEventListener('submit',function(e){e.preventDefault();const d=new FormData(this),name=String(d.get('name')||'').trim(),location=String(d.get('location')||'').trim(),message=String(d.get('message')||'').trim();if(name.length<2||name.length>80){guestbookStatus.textContent='Please enter your name.';guestbookStatus.className='guestbook-status error';return}if(message.length<3||message.length>600){guestbookStatus.textContent='Please enter a message of up to 600 characters.';guestbookStatus.className='guestbook-status error';return}const share=['🎉 Birthday message for Mme Mokorosi 🎉','',`From: ${name}`,location?`From: ${location}`:'','',`“${message}”`,'','Mokorosi Family 100th Birthday Celebration','31 October 2026'].filter(Boolean).join('\n');openWhatsApp(share);guestbookStatus.textContent='❤️ WhatsApp is ready with your birthday message. Tap Send to share it with the Mokorosi Family.';guestbookStatus.className='guestbook-status success'});
const lb=document.querySelector('#lightbox'),img=document.querySelector('#lightboxImage');if(lb&&img){document.querySelectorAll('[data-lightbox]').forEach(b=>b.addEventListener('click',()=>{img.src=b.dataset.lightbox;lb.hidden=false;document.body.style.overflow='hidden'}));function close(){lb.hidden=true;img.src='';document.body.style.overflow=''}document.querySelector('.lightbox-close')?.addEventListener('click',close);lb.addEventListener('click',e=>{if(e.target===lb)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!lb.hidden)close()})}
})();