(function(){
const countdown=document.querySelector('#countdown'),eventDate=new Date(countdown.dataset.event).getTime();
const els={days:document.querySelector('#days'),hours:document.querySelector('#hours'),minutes:document.querySelector('#minutes'),seconds:document.querySelector('#seconds')};
function tick(){const diff=Math.max(0,eventDate-Date.now());els.days.textContent=String(Math.floor(diff/86400000)).padStart(2,'0');els.hours.textContent=String(Math.floor(diff/3600000)%24).padStart(2,'0');els.minutes.textContent=String(Math.floor(diff/60000)%60).padStart(2,'0');els.seconds.textContent=String(Math.floor(diff/1000)%60).padStart(2,'0');if(!diff)document.querySelector('.countdown-heading strong').textContent='Today we celebrate!'}tick();setInterval(tick,1000);
const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('#site-nav');toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');toggle.setAttribute('aria-expanded','false')}));
function openWhatsApp(message,number='26662025872'){window.location.href='https://wa.me/'+number+'?text='+encodeURIComponent(message)}
document.querySelector('#reservationForm').addEventListener('submit',function(e){e.preventDefault();const d=new FormData(this),m=['Hello Mokorosi Family,','','I would like to make a reservation for Mme Mokorosi’s 100th Birthday Celebration.',`Name: ${d.get('name')}`,`Number of guests: ${d.get('guests')}`,`Contact number: ${d.get('phone')}`,d.get('note')?`Special note: ${d.get('note')}`:'','','Event: 31 October 2026 at 12:00 noon','Venue: BESA Meat & Chill, Corner Moshoeshoe & Caledon, Maseru West','Reservation contacts: +266 6202 5871 / +266 6202 5872'].filter(Boolean).join('\\n');openWhatsApp(m)});
const lb=document.querySelector('#lightbox'),img=document.querySelector('#lightboxImage');document.querySelectorAll('[data-lightbox]').forEach(b=>b.addEventListener('click',()=>{img.src=b.dataset.lightbox;lb.hidden=false;document.body.style.overflow='hidden'}));function close(){lb.hidden=true;img.src='';document.body.style.overflow=''}document.querySelector('.lightbox-close').addEventListener('click',close);lb.addEventListener('click',e=>{if(e.target===lb)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!lb.hidden)close()});
})();const guestbookForm=document.querySelector('#guestbookForm'),messagesWall=document.querySelector('#messagesWall'),messageCount=document.querySelector('#messageCount'),guestbookStatus=document.querySelector('#guestbookStatus'),refreshMessages=document.querySelector('#refreshMessages'),sbConfig=window.MOKOROSI_SUPABASE||{},supabaseClient=(window.supabase&&sbConfig.url&&sbConfig.anonKey&&!sbConfig.url.includes('YOUR_'))?window.supabase.createClient(sbConfig.url,sbConfig.anonKey):null;
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]))}
function formatDate(value){try{return new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric'}).format(new Date(value))}catch{return ''}}
function renderMessages(rows){const safeRows=Array.isArray(rows)?rows:[];messageCount.textContent=safeRows.length+' message'+(safeRows.length===1?'':'s');if(!safeRows.length){messagesWall.innerHTML='<div class="messages-empty">Be the first to leave a message of love for Mme Mokorosi. ❤️</div>';return}messagesWall.innerHTML=safeRows.map(row=>'<article class="message-card"><p>'+escapeHtml(row.message)+'</p><div class="message-meta"><span><strong>'+escapeHtml(row.name)+'</strong>'+(row.location?' · '+escapeHtml(row.location):'')+'</span><span>'+formatDate(row.created_at)+'</span></div></article>').join('')}
async function loadMessages(){if(!supabaseClient){messageCount.textContent='Setup required';messagesWall.innerHTML='<div class="messages-error">The celebration wall is ready. The family database connection still needs to be configured.</div>';return}messagesWall.innerHTML='<div class="messages-loading">Loading messages of love...</div>';const {data,error}=await supabaseClient.from('birthday_messages').select('id,name,location,message,created_at').order('created_at',{ascending:false}).limit(200);if(error){messagesWall.innerHTML='<div class="messages-error">Messages could not be loaded right now. Please try again.</div>';return}renderMessages(data)}
async function postGuestbookMessage(formData){if(!supabaseClient)throw new Error('The guestbook database has not been configured yet.');const name=String(formData.get('name')||'').trim(),location=String(formData.get('location')||'').trim(),message=String(formData.get('message')||'').trim();if(name.length<2||name.length>80)throw new Error('Please enter your name.');if(message.length<3||message.length>600)throw new Error('Please enter a message of up to 600 characters.');if(String(formData.get('website')||'').trim())throw new Error('Spam check failed.');const {data,error}=await supabaseClient.from('birthday_messages').insert({name,location:location||null,message}).select('id,name,location,message,created_at').single();if(error)throw error;return data}
if(guestbookForm){guestbookForm.addEventListener('submit',async e=>{e.preventDefault();guestbookStatus.className='guestbook-status';guestbookStatus.textContent='Saving your message...';const submit=guestbookForm.querySelector('button[type="submit"]');submit.disabled=true;try{const data=await postGuestbookMessage(new FormData(guestbookForm));guestbookForm.reset();guestbookStatus.className='guestbook-status success';guestbookStatus.textContent='❤️ Your message is now on the celebration wall!';await loadMessages();const share='A birthday message for Mme Mokorosi from '+data.name+': '+data.message+' — shared on the Mokorosi Family 100th Birthday Celebration website.';if(confirm('Your message has been posted! Would you also like to share it on WhatsApp?'))openWhatsApp(share,'26662025872')}catch(err){console.error(err);guestbookStatus.className='guestbook-status error';guestbookStatus.textContent=err.message||'We could not save your message. Please try again.'}finally{submit.disabled=false}});refreshMessages?.addEventListener('click',loadMessages);loadMessages()}